/*
  Do not edit this file, it is automatically generated from:
  </Users/catface/Documents/code/open-source/mysql/mysql-5.7.37/scripts/mysql_system_tables_data.sql>
*/
const char* mysql_system_data[]={
NULL
};
